In [1]:
#PCA excercise for heart disease

In [3]:
#import library

In [2]:
import pandas as pd
import numpy as np
from matplotlib.pyplot import plot
%matplotlib inline

In [4]:
#load the dataset
dataheart=pd.read_csv("heart.csv")
dataheart

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

EDA

In [5]:
dataheart.describe()


Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [6]:
dataheart.shape

(918, 12)

In [7]:
dataheart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [12]:
dataheart.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

#Treating outliers

In [13]:
dataheart[dataheart.Cholesterol>(dataheart.Cholesterol.mean()+3*dataheart.Cholesterol.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
76    32   M           ASY        118          529          0     Normal   
149   54   M           ASY        130          603          1     Normal   
616   67   F           NAP        115          564          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
76     130              N      0.0     Flat             1  
149    125              Y      1.0     Flat             1  
616    160              N      1.6     Flat             0

In [15]:
dataheart.shape

(918, 12)

In [16]:
dataheart1=dataheart[dataheart.Cholesterol<=(dataheart.Cholesterol.mean()+3*dataheart.Cholesterol.std())]

In [17]:
dataheart1.shape

(915, 12)

In [18]:
dataheart[dataheart.MaxHR>(dataheart.MaxHR.mean()+3*dataheart.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [19]:
dataheart[dataheart.FastingBS>(dataheart.FastingBS.mean()+3*dataheart.FastingBS.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [20]:
dataheart[dataheart.Oldpeak>(dataheart.Oldpeak.mean()+3*dataheart.Oldpeak.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
166   50   M           ASY        140          231          0         ST   
702   59   M            TA        178          270          0        LVH   
771   55   M           ASY        140          217          0     Normal   
791   51   M           ASY        140          298          0     Normal   
850   62   F           ASY        160          164          0        LVH   
900   58   M           ASY        114          318          0         ST   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
166    140              Y      5.0     Flat             1  
702    145              N      4.2     Down             0  
771    111              Y      5.6     Down             1  
791    122              Y      4.2     Flat             1  
850    145              N      6.2     Down             1  
900    140              N      4.4     Down             1

In [21]:
dataheart2=dataheart1[dataheart1.Oldpeak<=(dataheart1.Oldpeak.mean()+3*dataheart1.Oldpeak.std())]
dataheart2.shape

(909, 12)

In [22]:
dataheart[dataheart.RestingBP>(dataheart.RestingBP.mean()+3*dataheart.RestingBP.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
109   39   M           ATA        190          241          0     Normal   
241   54   M           ASY        200          198          0     Normal   
365   64   F           ASY        200            0          0     Normal   
399   61   M           NAP        200            0          1         ST   
592   61   M           ASY        190          287          1        LVH   
732   56   F           ASY        200          288          1        LVH   
759   54   M           ATA        192          283          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
109    106              N      0.0       Up             0  
241    142              Y      2.0     Flat             1  
365    140              Y      1.0     Flat             1  
399     70              N      0.0     Flat             1  
592    150              Y      2.0     Down             1  
732    133              Y      4.0     Down             1  
759    195              N      0.0       Up             1

In [24]:
dataheart3=dataheart2[dataheart2.RestingBP<=(dataheart2.RestingBP.mean()+3*dataheart2.RestingBP.std())]
dataheart3.shape

(902, 12)

In [25]:
dataheart.ChestPainType.unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [26]:
dataheart.RestingECG.unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [27]:
dataheart.ExerciseAngina.unique()

array(['N', 'Y'], dtype=object)

In [28]:
dataheart.ST_Slope.unique()

array(['Up', 'Flat', 'Down'], dtype=object)

Convert text columns to numbers using label encoding and one hot encoding

In [32]:
dataheart4=dataheart3.copy()
dataheart4.ExerciseAngina.replace(
          {'N':0,
            'Y':1},inplace=True)

dataheart4.ST_Slope.replace(
    {'Up':1,
    'Flat':2,
    'Down':3},inplace=True)
dataheart4.RestingECG.replace(
      {'Normal':1,
      'ST':2,
      'LVH':3},inplace=True)
dataheart4.head()


Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40   M           ATA        140          289          0           1   
1   49   F           NAP        160          180          0           1   
2   37   M           ATA        130          283          0           2   
3   48   F           ASY        138          214          0           1   
4   54   M           NAP        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         1             0  
1    156               0      1.0         2             1  
2     98               0      0.0         1             0  
3    108               1      1.5         2             1  
4    122               0      0.0         1             0

In [33]:
dataheart4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 902 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             902 non-null    int64  
 1   Sex             902 non-null    object 
 2   ChestPainType   902 non-null    object 
 3   RestingBP       902 non-null    int64  
 4   Cholesterol     902 non-null    int64  
 5   FastingBS       902 non-null    int64  
 6   RestingECG      902 non-null    int64  
 7   MaxHR           902 non-null    int64  
 8   ExerciseAngina  902 non-null    int64  
 9   Oldpeak         902 non-null    float64
 10  ST_Slope        902 non-null    int64  
 11  HeartDisease    902 non-null    int64  
dtypes: float64(1), int64(9), object(2)
memory usage: 91.6+ KB


In [34]:
dataheart5=pd.get_dummies(dataheart4,drop_first=True)
dataheart5.head()

Age  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  ExerciseAngina  \
0   40        140          289          0           1    172               0   
1   49        160          180          0           1    156               0   
2   37        130          283          0           2     98               0   
3   48        138          214          0           1    108               1   
4   54        150          195          0           1    122               0   

   Oldpeak  ST_Slope  HeartDisease  Sex_M  ChestPainType_ATA  \
0      0.0         1             0      1                  1   
1      1.0         2             1      0                  0   
2      0.0         1             0      1                  1   
3      1.5         2             1      0                  0   
4      0.0         1             0      1                  0   

   ChestPainType_NAP  ChestPainType_TA  
0                  0                 0  
1                  1                 0  
2                  0                 0  
3                  0                 0  
4                  1                 0

Define Dependent and independent variable

In [35]:
x=dataheart5.drop("HeartDisease",axis="columns")
y=dataheart5.HeartDisease

In [36]:
x

Age  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0     40        140          289          0           1    172   
1     49        160          180          0           1    156   
2     37        130          283          0           2     98   
3     48        138          214          0           1    108   
4     54        150          195          0           1    122   
..   ...        ...          ...        ...         ...    ...   
913   45        110          264          0           1    132   
914   68        144          193          1           1    141   
915   57        130          131          0           1    115   
916   57        130          236          0           3    174   
917   38        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  Sex_M  ChestPainType_ATA  \
0                 0      0.0         1      1                  1   
1                 0      1.0         2      0                  0   
2                 0      0.0         1      1                  1   
3                 1      1.5         2      0                  0   
4                 0      0.0         1      1                  0   
..              ...      ...       ...    ...                ...   
913               0      1.2         2      1                  0   
914               0      3.4         2      1                  0   
915               1      1.2         2      1                  0   
916               0      0.0         2      0                  1   
917               0      0.0         1      1                  0   

     ChestPainType_NAP  ChestPainType_TA  
0                    0                 0  
1                    1                 0  
2                    0                 0  
3                    0                 0  
4                    1                 0  
..                 ...               ...  
913                  0                 1  
914                  0                 0  
915                  0                 0  
916                  0                 0  
917                  1                 0  

[902 rows x 13 columns]

In [37]:
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 902, dtype: int64

Scaling

In [38]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
x_scaled=scalar.fit_transform(x)
x_scaled

array([[-1.42896269,  0.46089071,  0.85238015, ...,  2.06757196,
        -0.53547478, -0.22914788],
       [-0.47545956,  1.5925728 , -0.16132855, ..., -0.4836591 ,
         1.86750159, -0.22914788],
       [-1.74679706, -0.10495034,  0.79657967, ...,  2.06757196,
        -0.53547478, -0.22914788],
       ...,
       [ 0.37209878, -0.10495034, -0.61703246, ..., -0.4836591 ,
        -0.53547478, -0.22914788],
       [ 0.37209878, -0.10495034,  0.35947592, ...,  2.06757196,
        -0.53547478, -0.22914788],
       [-1.64085227,  0.3477225 , -0.20782894, ..., -0.4836591 ,
         1.86750159, -0.22914788]])

spliting into train and test data

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=30)

In [40]:
x_train.shape

(721, 13)

In [41]:
x_test.shape

(181, 13)

Model-Random Forest

In [42]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier()
model_rf.fit(x_train,y_train)
model_rf.score(x_test,y_test)

0.8674033149171271

PCA-Dimension Reduction

In [43]:
x

Age  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0     40        140          289          0           1    172   
1     49        160          180          0           1    156   
2     37        130          283          0           2     98   
3     48        138          214          0           1    108   
4     54        150          195          0           1    122   
..   ...        ...          ...        ...         ...    ...   
913   45        110          264          0           1    132   
914   68        144          193          1           1    141   
915   57        130          131          0           1    115   
916   57        130          236          0           3    174   
917   38        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  Sex_M  ChestPainType_ATA  \
0                 0      0.0         1      1                  1   
1                 0      1.0         2      0                  0   
2                 0      0.0         1      1                  1   
3                 1      1.5         2      0                  0   
4                 0      0.0         1      1                  0   
..              ...      ...       ...    ...                ...   
913               0      1.2         2      1                  0   
914               0      3.4         2      1                  0   
915               1      1.2         2      1                  0   
916               0      0.0         2      0                  1   
917               0      0.0         1      1                  0   

     ChestPainType_NAP  ChestPainType_TA  
0                    0                 0  
1                    1                 0  
2                    0                 0  
3                    0                 0  
4                    1                 0  
..                 ...               ...  
913                  0                 1  
914                  0                 0  
915                  0                 0  
916                  0                 0  
917                  1                 0  

[902 rows x 13 columns]

In [44]:
from sklearn.decomposition import PCA
pca=PCA(0.95)
x_pca=pca.fit_transform(x)
x_pca

array([[ 93.82465373, -29.40099458],
       [-15.58422331, -14.10909233],
       [ 83.29606634,  38.6867453 ],
       ...,
       [-67.57318721,  17.61319354],
       [ 40.70458237, -33.38750602],
       [-19.91368346, -37.29085722]])

In [46]:
x_pca.shape

(902, 2)

In [47]:
pca.explained_variance_ratio_

array([0.92010766, 0.05065984])

In [48]:
pca.n_components_

2

In [49]:
x_train_pca,x_test_pca,y_train,y_test=train_test_split(x_pca,y,test_size=0.2,random_state=30)

In [50]:
model=RandomForestClassifier()
model.fit(x_train_pca,y_train)
model.score(x_test_pca,y_test)

0.7016574585635359

pca -->no of compontent


In [51]:
pca=PCA(n_components=5)
x_pca=pca.fit_transform(x)
x_pca

array([[ 93.82465373, -29.40099458, -11.5858984 ,  -9.15231708,
         -0.65829822],
       [-15.58422331, -14.10909233, -31.680368  ,  -5.8600424 ,
          0.18600958],
       [ 83.29606634,  38.6867453 ,  15.39992052, -21.17520932,
         -0.95623549],
       ...,
       [-67.57318721,  17.61319354,   4.35202042,   0.39314922,
          0.32347141],
       [ 40.70458237, -33.38750602,  -5.99332666,   9.13615483,
         -0.57449558],
       [-19.91368346, -37.29085722, -13.31321738, -10.99404687,
         -0.45488669]])

In [52]:
x_train_pca,x_test_pca,y_train,y_test=train_test_split(x_pca,y,test_size=0.2,random_state=30)
model=RandomForestClassifier()
model.fit(x_train_pca,y_train)
model.score(x_test_pca,y_test)

0.8066298342541437

In [54]:
pca=PCA(n_components=2)
x_pca=pca.fit_transform(x)
x_pca

array([[ 93.82465373, -29.40099458],
       [-15.58422331, -14.10909233],
       [ 83.29606634,  38.6867453 ],
       ...,
       [-67.57318721,  17.61319354],
       [ 40.70458237, -33.38750602],
       [-19.91368346, -37.29085722]])

In [55]:
x_train_pca,x_test_pca,y_train,y_test=train_test_split(x_pca,y,test_size=0.2,random_state=30)
model=RandomForestClassifier()
model.fit(x_train_pca,y_train)
model.score(x_test_pca,y_test)

0.7513812154696132